import { create } from 'zustand';
import { persist } from 'zustand/middleware';

type Language = 'th' | 'en' | 'zh';

interface LanguageStore {
  language: Language;
  setLanguage: (lang: Language) => void;
}

export const useLanguage = create<LanguageStore>()(
  persist(
    (set) => ({
      language: 'th',
      setLanguage: (lang) => set({ language: lang }),
    }),
    {
      name: 'language-storage',
    }
  )
);

export const translations = {
  th: {
    // Header
    home: "หน้าแรก",
    about: "เกี่ยวกับเรา",
    rooms: "ห้องพัก",
    menu: "เมนู",
    gallery: "แกลเลอรี",
    reviews: "รีวิว",
    contact: "ติดต่อเรา",
    forum: "เว็บบอร์ด",
    bookNow: "จองเลย",
    
    // Hero
    location: "กรุงเทพ ดอนเมือง, ประเทศไทย",
    heroTitle: "Plern Ping Cafe",
    heroSubtitle: "สัมผัสการผสมผสานที่ลงตัวระหว่างเสน่ห์ล้านนาแท้และความสะดวกสบายสมัยใหม่",
    heroDescription: "ท่ามกลางธรรมชาติที่สงบ ที่ซึ่งอาหารรสเลิศผสานกับกาแฟชั้นเยี่ยมในสวนอันเงียบสงบ",
    exploreMenu: "สำรวจเมนู",
    viewRooms: "ดูห้องพัก",
    
    // Features
    featuresTitle: "ทำไมต้องเลือก Plern Ping",
    featuresSubtitle: "ประสบการณ์ที่ไม่เหมือนใคร",
    traditionalArchitecture: "สถาปัตยกรรมล้านนาแท้",
    traditionalArchitectureDesc: "บ้านไม้สไตล์ล้านนาที่สวยงามในบรรยากาศธรรมชาติ",
    artisanCoffee: "กาแฟชั้นเยี่ยม",
    artisanCoffeeDesc: "เมือกาแฟคั่วพิเศษและเครื่องดื่มสไตล์ไทย",
    authenticCuisine: "อาหารไทยแท้",
    authenticCuisineDesc: "อาหารล้านนาและไทยต้นตำรับจากเชฟท้องถิ่น",
    gardenSetting: "ในสวนธรรมชาติ",
    gardenSettingDesc: "ที่นั่งในร่มและกลางแจ้งท่ามกลางสวนเขียวขจี",
    
    // Events
    eventsTitle: "ห้องประชุม & งานเลี้ยง",
    eventsSubtitle: "พื้นที่จองแบบพิเศษสำหรับการจัดงาน การนำเสนอ และงานสังสรรค์ รองรับได้ทุกรูปแบบ",
    eventsMainTitle: "คาแฟล้านนาและห้องอเนกประสงค์",
    eventsMainDesc: "พื้นที่ห้องแบบพิเศษพร้อมอุปกรณ์ทุกสิ่งอย่าง ตั้งแต่การประชุม การนำเสนอ ไปจนถึงงานสังสรรค์ พร้อมบริการจัดเลี้ยงและอุปกรณ์ครบครัน",
    ourServices: "บริการของเรา",
    presentationRoom: "ห้องบรรยาย/นำเสนอ",
    presentationRoomDesc: "พร้อมโปรเจคเตอร์ ระบบเสียง และระบบควบคุมความเข้าใจ",
    cateringService: "บริการจัดเลี้ยง",
    cateringServiceDesc: "อาหารและเครื่องดื่มคุณภาพ ปรับเมนูตามความต้องการ",
    privateEvents: "ห้องการไอทีและส่วนตัว",
    privateEventsDesc: "เหมาะสำหรับงานเป็นใช้ งานเชื่อมต่อส่วนตัวหรือ และงานส่วนตัว",
    inquirePrice: "สอบถามราคาเลี้ยง",
    presentationRoomShort: "ห้องนำเสนอ",
    presentationRoomShortDesc: "ห้องบรรยายพร้อมอุปกรณ์ทันสมัยนี้",
    cateringServiceShort: "รับจัดเลี้ยง",
    cateringServiceShortDesc: "บริการจัดเลี้ยงครบวงจร",
    
    // Rooms
    roomsTitle: "ห้องพักของเรา",
    roomsSubtitle: "พักผ่อนในความสะดวกสบายและสไตล์ล้านนา",
    perNight: "/ คืน",
    deluxeRoom: "ห้องดีลักซ์",
    deluxeRoomDesc: "ห้องพักกว้างขวางพร้อมการตกแต่งสไตล์ล้านนาสมัยใหม่",
    familySuite: "ห้องสวีทครอบครัว",
    familySuiteDesc: "ห้องพักขนาดใหญ่สำหรับครอบครัว มีห้องนอน 2 ห้อง",
    gardenView: "ห้องวิวสวน",
    gardenViewDesc: "ห้องพักสบายๆ พร้อมวิวสวนเขียวขจี",
    bookRoom: "จองห้องพัก",
    
    // Menu
    menuTitle: "เมนูของเรา",
    menuSubtitle: "อาหารไทยแท้และกาแฟพรีเมียมที่รังสรรค์ด้วยใจ",
    coffeeAndDrinks: "กาแฟและเครื่องดื่ม",
    food: "อาหาร",
    espresso: "เอสเพรสโซ",
    espressoDesc: "ช็อตเดี่ยวเข้มข้น กลิ่นหอมเต็มที่",
    cappuccino: "คาปูชิโน",
    cappuccinoDesc: "เอสเพรสโซกับฟองนมนุ่ม",
    latte: "ลาเต้",
    latteDesc: "เอสเพรสโซนุ่มนวลกับนมครีมมี่",
    thaiIcedCoffee: "กาแฟเย็นสไตล์ไทย",
    thaiIcedCoffeeDesc: "สไตล์ดั้งเดิมกับนมข้นหวาน",
    padThai: "ผัดไทย",
    padThaiDesc: "เส้นผัดสไตล์ไทยคลาสสิก",
    greenCurry: "แกงเขียวหวาน",
    greenCurryDesc: "แกงเขียวหวานหอมกรุ่นกับไก่",
    somTam: "ส้มตำ",
    somTamDesc: "ส้มตำสไตล์ล้านนาเผ็ดร้อน",
    khaoSoi: "ข้าวซอย",
    khaoSoiDesc: "ก๋วยเตี๋ยวแกงกะหรี่เหนือ",
    viewFullMenu: "ดูเมนูทั้งหมด",
    recommended: "เมนูแนะนำ",
    recommendedSubtitle: "เมนูสุดพิเศษที่คุณไม่ควรพลาด",
    
    // Gallery
    galleryTitle: "แกลเลอรี",
    gallerySubtitle: "เหลือบมองสถานที่อันเงียบสงบของเรา",
    
    // Reviews
    reviewsTitle: "รีวิวจากลูกค้า",
    reviewsSubtitle: "ความประทับใจจากผู้ที่มาเยือน",
    
    // Contact
    contactTitle: "ติดต่อเรา",
    contactSubtitle: "เรายินดีที่จะตอบคำถามและช่วยเหลือคุณในการจองห้องพัก",
    phone: "โทรศัพท์",
    email: "อีเมล",
    socialMedia: "โซเชียลมีเดีย",
    address: "ที่อยู่",
    openingHours: "เวลาเปิด-ปิด",
    lineId: "Line ID",
    sendMessageForm: "ส่งข้อความถึงเรา",
    nameLabel: "ชื่อ",
    emailLabel: "อีเมล",
    phoneLabel: "เบอร์โทร",
    topicLabel: "หัวข้อ",
    messageLabel: "ข้อความ",
    sendMessage: "ส่งข้อความ",
    namePlaceholder: "กรุณากรอกชื่อของคุณ",
    emailPlaceholder: "กรุณากรอกอีเมล",
    phonePlaceholder: "กรุณากรอกเบอร์โทร",
    topicPlaceholder: "กรุณากรอกหัวข้อ",
    messagePlaceholder: "กรุณากรอกข้อความของคุณ",
    messageSent: "ส่งข้อความสำเร็จ",
    messageSuccess: "ขอบคุณที่ติดต่อเรา เราจะติดต่อกลับโดยเร็วที่สุด",
    dailyOpen: "วันทุกวันเฉพาะต์ 08:00 - 21:00 (ตามเวลาท้องถิ่น)",
    
    // Forum
    forumTitle: "เว็บบอร์ด",
    forumSubtitle: "พูดคุยและแบ่งปันประสบการณ์",
    latestTopics: "กระทู้ล่าสุด",
    popularTopics: "กระทู้ยอดนิยม",
    replies: "ตอบกลับ",
    views: "ครั้ง",
    lastPost: "โพสต์ล่าสุด",
    startedBy: "เริ่มโดย",
    
    // Footer
    footerDescription: "สัมผัสการผสมผสานที่ลงตัวระหว่างอาหารไทยแท้และกาแฟชั้นเยี่ยมในบรรยากาศสวนธรรมชาติ",
    contactUs: "ติดต่อเรา",
    quickLinks: "ลิงก์ด่วน",
    followUs: "ติดตามเรา",
    allRightsReserved: "สงวนลิขสิทธิ์",
  },
  en: {
    // Header
    home: "Home",
    about: "About",
    rooms: "Rooms",
    menu: "Menu",
    gallery: "Gallery",
    reviews: "Reviews",
    contact: "Contact",
    forum: "Forum",
    bookNow: "Book Now",
    
    // Hero
    location: "Bangkok Don Mueang, Thailand",
    heroTitle: "Plern Ping Cafe",
    heroSubtitle: "Experience the perfect blend of traditional Lanna charm and modern comfort",
    heroDescription: "Nestled in nature's embrace, where exceptional food meets artisan coffee in a tranquil garden setting",
    exploreMenu: "Explore Menu",
    viewRooms: "View Rooms",
    
    // Features
    featuresTitle: "Why Choose Plern Ping",
    featuresSubtitle: "A unique experience awaits",
    traditionalArchitecture: "Traditional Architecture",
    traditionalArchitectureDesc: "Beautiful Lanna-style wooden houses in natural surroundings",
    artisanCoffee: "Artisan Coffee",
    artisanCoffeeDesc: "Specialty roasted coffee and Thai-style beverages",
    authenticCuisine: "Authentic Cuisine",
    authenticCuisineDesc: "Authentic Lanna and Thai dishes from local chefs",
    gardenSetting: "Garden Setting",
    gardenSettingDesc: "Indoor and outdoor seating amid lush greenery",
    
    // Events
    eventsTitle: "Conference Room & Events",
    eventsSubtitle: "Special event spaces for meetings, presentations, and gatherings supporting all formats",
    eventsMainTitle: "Lanna Cafe and Multi-purpose Room",
    eventsMainDesc: "Special room facilities with all equipment, from meetings and presentations to social gatherings, with complete catering services and equipment",
    ourServices: "Our Services",
    presentationRoom: "Presentation/Seminar Room",
    presentationRoomDesc: "With projector, sound system and connectivity control",
    cateringService: "Catering Service",
    cateringServiceDesc: "Quality food and beverages with customizable menus",
    privateEvents: "IT & Private Events",
    privateEventsDesc: "Perfect for business use, private connections and personal events",
    inquirePrice: "Inquire Event Pricing",
    presentationRoomShort: "Presentation Room",
    presentationRoomShortDesc: "Modern equipped seminar room",
    cateringServiceShort: "Catering",
    cateringServiceShortDesc: "Full-service event catering",
    
    // Rooms
    roomsTitle: "Our Rooms",
    roomsSubtitle: "Relax in comfort and Lanna style",
    perNight: "/ night",
    deluxeRoom: "Deluxe Room",
    deluxeRoomDesc: "Spacious room with modern Lanna-style decoration",
    familySuite: "Family Suite",
    familySuiteDesc: "Large room for families with 2 bedrooms",
    gardenView: "Garden View Room",
    gardenViewDesc: "Cozy room with lush garden views",
    bookRoom: "Book Room",
    
    // Menu
    menuTitle: "Our Menu",
    menuSubtitle: "Authentic Thai cuisine and premium coffee crafted with passion",
    coffeeAndDrinks: "Coffee & Drinks",
    food: "Food",
    espresso: "Espresso",
    espressoDesc: "Rich, bold single shot",
    cappuccino: "Cappuccino",
    cappuccinoDesc: "Espresso with steamed milk foam",
    latte: "Latte",
    latteDesc: "Smooth espresso with creamy milk",
    thaiIcedCoffee: "Thai Iced Coffee",
    thaiIcedCoffeeDesc: "Traditional style with condensed milk",
    padThai: "Pad Thai",
    padThaiDesc: "Classic Thai stir-fried noodles",
    greenCurry: "Green Curry",
    greenCurryDesc: "Aromatic Thai green curry with chicken",
    somTam: "Som Tam",
    somTamDesc: "Spicy papaya salad, Lanna style",
    khaoSoi: "Khao Soi",
    khaoSoiDesc: "Northern Thai curry noodle soup",
    viewFullMenu: "View Full Menu",
    recommended: "Recommended Menu",
    recommendedSubtitle: "Special dishes you shouldn't miss",
    
    // Gallery
    galleryTitle: "Gallery",
    gallerySubtitle: "A glimpse into our serene sanctuary",
    
    // Reviews
    reviewsTitle: "Customer Reviews",
    reviewsSubtitle: "Experiences from our visitors",
    
    // Contact
    contactTitle: "Contact Us",
    contactSubtitle: "We're happy to answer your questions and assist with room bookings",
    phone: "Phone",
    email: "Email",
    socialMedia: "Social Media",
    address: "Address",
    openingHours: "Opening Hours",
    lineId: "Line ID",
    sendMessageForm: "Send Us a Message",
    nameLabel: "Name",
    emailLabel: "Email",
    phoneLabel: "Phone",
    topicLabel: "Topic",
    messageLabel: "Message",
    sendMessage: "Send Message",
    namePlaceholder: "Please enter your name",
    emailPlaceholder: "Please enter your email",
    phonePlaceholder: "Please enter your phone number",
    topicPlaceholder: "Please enter topic",
    messagePlaceholder: "Please enter your message",
    messageSent: "Message Sent Successfully",
    messageSuccess: "Thank you for contacting us. We will get back to you as soon as possible",
    dailyOpen: "Daily 08:00 - 21:00 (Local Time)",
    
    // Forum
    forumTitle: "Forum",
    forumSubtitle: "Share your experiences",
    latestTopics: "Latest Topics",
    popularTopics: "Popular Topics",
    replies: "Replies",
    views: "Views",
    lastPost: "Last Post",
    startedBy: "Started by",
    
    // Footer
    footerDescription: "Experience the perfect blend of authentic Thai cuisine and artisan coffee in a natural garden setting",
    contactUs: "Contact Us",
    quickLinks: "Quick Links",
    followUs: "Follow Us",
    allRightsReserved: "All rights reserved",
  },
  zh: {
    // Header
    home: "首页",
    about: "关于我们",
    rooms: "客房",
    menu: "菜单",
    gallery: "画廊",
    reviews: "评论",
    contact: "联系我们",
    forum: "论坛",
    bookNow: "立即预订",
    
    // Hero
    location: "泰国曼谷廊曼",
    heroTitle: "Plern Ping 咖啡馆",
    heroSubtitle: "体验传统兰纳魅力与现代舒适的完美融合",
    heroDescription: "坐落在大自然的怀抱中，在宁静的花园环境中，特色美食与精品咖啡相遇",
    exploreMenu: "探索菜单",
    viewRooms: "查看客房",
    
    // Features
    featuresTitle: "为什么选择 Plern Ping",
    featuresSubtitle: "独特的体验等着您",
    traditionalArchitecture: "传统建筑",
    traditionalArchitectureDesc: "自然环境中美丽的兰纳风格木屋",
    artisanCoffee: "精品咖啡",
    artisanCoffeeDesc: "特色烘焙咖啡和泰式饮品",
    authenticCuisine: "正宗美食",
    authenticCuisineDesc: "来自当地厨师的正宗兰纳和泰国菜肴",
    gardenSetting: "花园环境",
    gardenSettingDesc: "郁郁葱葱的绿色植物中的室内外座位",
    
    // Events
    eventsTitle: "会议室及活动",
    eventsSubtitle: "支持各种形式的会议、演示和聚会的特殊活动空间",
    eventsMainTitle: "兰纳咖啡馆和多功能厅",
    eventsMainDesc: "配备所有设备的特殊房间设施，从会议和演示到社交聚会，提供完整的餐饮服务和设备",
    ourServices: "我们的服务",
    presentationRoom: "演示/研讨室",
    presentationRoomDesc: "配备投影仪、音响系统和连接控制",
    cateringService: "餐饮服务",
    cateringServiceDesc: "优质的食品和饮料，可定制菜单",
    privateEvents: "IT和私人活动",
    privateEventsDesc: "非常适合商务用途、私人连接和个人活动",
    inquirePrice: "咨询活动价格",
    presentationRoomShort: "演示室",
    presentationRoomShortDesc: "现代化设备齐全的研讨室",
    cateringServiceShort: "餐饮",
    cateringServiceShortDesc: "全方位活动餐饮服务",
    
    // Rooms
    roomsTitle: "我们的客房",
    roomsSubtitle: "在舒适和兰纳风格中放松",
    perNight: "/ 晚",
    deluxeRoom: "豪华客房",
    deluxeRoomDesc: "宽敞的客房，装饰有现代兰纳风格",
    familySuite: "家庭套房",
    familySuiteDesc: "适合家庭的大房间，有2间卧室",
    gardenView: "花园景观房",
    gardenViewDesc: "舒适的客房，可欣赏郁郁葱葱的花园景色",
    bookRoom: "预订客房",
    
    // Menu
    menuTitle: "我们的菜单",
    menuSubtitle: "用心制作的正宗泰国美食和精品咖啡",
    coffeeAndDrinks: "咖啡和饮品",
    food: "食物",
    espresso: "浓缩咖啡",
    espressoDesc: "浓郁大胆的单份咖啡",
    cappuccino: "卡布奇诺",
    cappuccinoDesc: "浓缩咖啡配蒸奶泡",
    latte: "拿铁",
    latteDesc: "顺滑的浓缩咖啡配奶油牛奶",
    thaiIcedCoffee: "泰式冰咖啡",
    thaiIcedCoffeeDesc: "传统风格配炼乳",
    padThai: "泰式炒面",
    padThaiDesc: "经典泰式炒面",
    greenCurry: "绿咖喱",
    greenCurryDesc: "芳香泰式绿咖喱配鸡肉",
    somTam: "青木瓜沙拉",
    somTamDesc: "兰纳风格的辣木瓜沙拉",
    khaoSoi: "清迈咖喱面",
    khaoSoiDesc: "泰北咖喱面汤",
    viewFullMenu: "查看完整菜单",
    recommended: "推荐菜单",
    recommendedSubtitle: "您不应错过的特色菜肴",
    
    // Gallery
    galleryTitle: "画廊",
    gallerySubtitle: "一瞥我们宁静的圣地",
    
    // Reviews
    reviewsTitle: "客户评论",
    reviewsSubtitle: "来自访客的体验",
    
    // Contact
    contactTitle: "联系我们",
    contactSubtitle: "我们很乐意回答您的问题并协助预订客房",
    phone: "电话",
    email: "电子邮件",
    socialMedia: "社交媒体",
    address: "地址",
    openingHours: "营业时间",
    lineId: "Line ID",
    sendMessageForm: "给我们发送消息",
    nameLabel: "姓名",
    emailLabel: "电子邮件",
    phoneLabel: "电话",
    topicLabel: "主题",
    messageLabel: "消息",
    sendMessage: "发送消息",
    namePlaceholder: "请输入您的姓名",
    emailPlaceholder: "请输入您的电子邮件",
    phonePlaceholder: "请输入您的电话号码",
    topicPlaceholder: "请输入主题",
    messagePlaceholder: "请输入您的消息",
    messageSent: "消息发送成功",
    messageSuccess: "感谢您联系我们。我们会尽快回复您",
    dailyOpen: "每天 08:00 - 21:00（当地时间）",
    
    // Forum
    forumTitle: "论坛",
    forumSubtitle: "分享您的经验",
    latestTopics: "最新主题",
    popularTopics: "热门主题",
    replies: "回复",
    views: "浏览",
    lastPost: "最后发表",
    startedBy: "发起人",
    
    // Footer
    footerDescription: "在自然花园环境中体验正宗泰国美食与精品咖啡的完美融合",
    contactUs: "联系我们",
    quickLinks: "快速链接",
    followUs: "关注我们",
    allRightsReserved: "版权所有",
  },
};
